version: '3.7'
services: 

    dradis:

        container_name: dradis
        image: evait/dradis-ce
        volumes:
            - $PWD/dradis/dbdata:/dbdata
            - $PWD/dradis/templates:/opt/dradis-ce/templates
        ports: 
            - 3010:3000
        links: 
            - redis

    redis:

        container_name: redis
        image: redis

    dvwap:

        container_name: dvwap
        image: vulnerables/web-dvwa
        ports: 
            - 8082:80